# Generated by Django 5.1.3 on 2024-11-12 15:27

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_post_subtitle_alter_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_portada',
            field=models.ImageField(blank=True, default='image_default.jpg', null=True, upload_to=''),
        ),
    ]
